# Sentiment Analysis - Exercise

## Necessary imports

In order to handle the data properly we have to import the data and the modules we need:

In [38]:
# modules
import pandas as pd
import numpy as np
import re
import nltk
from bs4 import BeautifulSoup
from sklearn.preprocessing import LabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

First of all, you need to download the data set "tweets.csv" from the GitHub repository https://github.com/assenmacher-mat/nlp_notebooks.

__If you are running this notebook on colab (https://colab.research.google.com/), you also need to run the next chunk in order to upload the data to colab.  
Choose it in the upload window and in it will be available on colab from now on.__  
(If you are running this notebook locally on your machine, you can skip the execution of this chunk)

In [ ]:
from google.colab import files
uploaded = files.upload()

### Import the data set

__If you are running this notebook locally on your machine, you might need to adjust the path (depending on where you've saved the data).__  
(If you are running this notebook on colab, you can can leave the path unchanged)

In [7]:
imdb = pd.read_csv("imdb.csv", encoding = "utf-8")

### Next, just have a look at the data set in order to see what's inside

In [8]:
imdb.loc[:3,:]

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative

In [36]:
reviews_raw = [doc for doc in list(imdb.review)]
sentiments = [sent for sent in list(imdb.sentiment)]

In [13]:
reviews_clean = [BeautifulSoup(rev, "html.parser").text for rev in reviews_raw]

In [14]:
reviews_clean[:5]

["One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows w

### Labels in the right format

In [40]:
labels=LabelBinarizer().fit_transform(sentiments)
print(labels.shape)

(50000, 1)


### Transform the corpus to a Bag-of-words

In [30]:
unigram_vectorizer = CountVectorizer(ngram_range = (1,1), min_df = 10, binary = False, max_features = 10000)
bow = unigram_vectorizer.fit_transform(reviews_clean)

In [33]:
print(bow.toarray())
print(bow.toarray().shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(50000, 10000)
